manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: datapointchris
      url-base: https://github.com/datapointchris
  projects:
    - name: zmk-shared
      remote: datapointchris
      revision: main
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
  self:
    path: config
